version: "3.7"
services:
 api:
  build:
   context: .
   target: build
  environment:
   - NODE_ENV=development
   - PORT=4000
  volumes:
   - ./:/app
   - /app/node_modules
  ports:
   - 4000:4000
  command: pnpm dev
